"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { StatusBadge, recipientNames, recipientSummary, type Application } from "@/components/views/shared"
import { Undo2 } from "lucide-react"

export function ApplicationTable({ items, onTransfer, onRevoke, busy=false }: { items: Application[]; onTransfer?:(item:Application)=>Promise<void>; onRevoke?:(item:Application)=>Promise<void>; busy?:boolean }) {
  return <Table><TableHeader><TableRow><TableHead>发送单 / 文件</TableHead><TableHead>发送人</TableHead><TableHead>收件人</TableHead><TableHead>状态</TableHead><TableHead className="text-right">操作 / 时间</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => {
    const activeDeliveries = (item.deliveries || []).filter((delivery) => delivery.enabled && !delivery.revokedAt)
    return <TableRow key={item.id}><TableCell><a className="font-medium text-cyan-800 hover:underline" href={`/api/files/${item.id}`}>{item.fileName}</a><p className="mt-1 text-xs text-slate-500">{item.id} · {item.size}</p></TableCell><TableCell><p>{item.requester}</p><p className="mt-1 text-xs text-slate-500">{item.department}</p></TableCell><TableCell className="max-w-[220px] truncate" title={recipientNames(item).join("、")}>{recipientSummary(item)}</TableCell><TableCell><StatusBadge status={item.status} />{item.typeMismatch && <Badge variant="outline" className="ml-1 border-rose-200 bg-rose-50 text-rose-700" title={`实际内容类型：${item.detectedKind || "未知"}`}>后缀与内容不符</Badge>}{item.reason && <p className={`mt-1 max-w-[220px] truncate text-xs ${["REJECTED","REJECTED_BY_RULE","TRANSFER_FAILED"].includes(item.status) ? "text-rose-600" : "text-amber-700"}`} title={item.reason}>{item.reason}</p>}</TableCell><TableCell className="text-right"><p className="text-slate-500">{item.createdAt}</p><div className="mt-2 flex flex-wrap justify-end gap-2">{onTransfer && ["APPROVED","TRANSFER_FAILED"].includes(item.status) && <Button size="sm" variant="outline" disabled={busy} onClick={()=>void onTransfer(item)}>{item.status==="TRANSFER_FAILED"?"重试送达":"执行送达"}</Button>}{onRevoke && item.status === "TRANSFERRED" && activeDeliveries.length > 0 && <Button size="sm" variant="ghost" className="text-rose-600 hover:text-rose-700" disabled={busy} onClick={()=>void onRevoke?.(item)}><Undo2 className="size-4" />撤回</Button>}{item.status === "TRANSFERRED" && activeDeliveries.length === 0 && <Badge variant="outline" className="border-slate-200 bg-slate-50 text-slate-500">已撤回</Badge>}</div>{item.status === "TRANSFERRED" && item.deliveries && item.deliveries.length > 0 && <p className="mt-2 text-[11px] text-slate-500">下载 {item.deliveries.reduce((sum, delivery) => sum + (delivery.downloadCount || 0), 0)} 次{activeDeliveries.length === 0 ? " · 已全部撤回" : ` · ${activeDeliveries.filter((delivery) => delivery.firstDownloadedAt).length}/${activeDeliveries.length} 人已下载`}</p>}</TableCell></TableRow>
  })}</TableBody></Table>
}
