"use client"

import { useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { SectionTitle, recipientNames, recipientSummary, type Application } from "@/components/views/shared"
import { BadgeCheck, Check, FileArchive, X } from "lucide-react"

export function ApprovalsView({ items, currentUser, onDecision }: { items: Application[]; currentUser: { displayName: string; email: string; role: string }; onDecision:(item:Application,d:"approve"|"reject")=>void }) {
  const [expanded, setExpanded] = useState<string | null>(null)
  return <div className="space-y-7"><SectionTitle eyebrow="单级审批" title="待我审批" description="审批通过后系统立即送达站内收件人；驳回必须填写理由，发起人可修改后重新提交。规则可指派指定审批人，未指定时按角色轮询。" /><div className="space-y-4">{items.length ? items.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="grid size-12 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><FileArchive className="size-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{item.fileName}</h2>{index===0&&<Badge className="bg-rose-50 text-rose-700">即将超时</Badge>}{item.approver && <Badge className="bg-cyan-50 text-cyan-700">指定审批人 {item.approver}</Badge>}{item.typeMismatch && <Badge variant="outline" className="border-rose-200 bg-rose-50 text-rose-700" title={`实际内容类型：${item.detectedKind || "未知"}`}>后缀与内容不符，请人工核实真实格式</Badge>}</div><p className="mt-2 text-sm text-slate-500">{item.id} · {item.size} · {item.requester} / {item.department}</p><p className="mt-3 text-xs text-slate-600">收件人：{recipientSummary(item, 5)}（共 {recipientNames(item).length} 人）　规则：{item.rule}　提交：{item.createdAt}</p>{item.reason && <p className="mt-2 text-xs leading-5 text-slate-600">判定说明：{item.reason}</p>}<button className="mt-2 text-xs text-cyan-700 hover:underline" onClick={()=>setExpanded(expanded===item.id?null:item.id)}>{expanded===item.id?"收起详情":"查看发送说明"}</button>{expanded===item.id && item.detail && <p className="mt-2 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600">{item.detail}</p>}</div><div className="flex gap-2">{item.requesterEmail && item.requesterEmail.toLowerCase() === currentUser.email?.toLowerCase() && currentUser.role !== "管理员" ? <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-700">本人提交，需他人审批</Badge> : <>{item.requesterEmail && item.requesterEmail.toLowerCase() === currentUser.email?.toLowerCase() && <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-700">本人提交</Badge>}<Button variant="outline" onClick={()=>onDecision(item,"reject")}><X />驳回</Button><Button onClick={()=>onDecision(item,"approve")}><Check />通过</Button></>}</div></div></div>):<div className="rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center"><BadgeCheck className="mx-auto size-10 text-emerald-600" /><h2 className="mt-4 font-semibold">当前没有待审批申请</h2><p className="mt-1 text-sm text-slate-500">当前身份：{currentUser.displayName}（{currentUser.role}）</p></div>}</div></div> }
