"use client"

import { useEffect, useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { SectionTitle, ruleActionStyle, statusStyle, type ApiError, type RuleItem } from "@/components/views/shared"
import { Pencil, Plus, Trash2 } from "lucide-react"

export function RulesView({ items, refresh, setNotice, setError, role }: { items: RuleItem[]; refresh:()=>Promise<void>; setNotice:(v:string)=>void; setError:(v:string)=>void; role:string }) {
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<RuleItem | null>(null)
  // 内容类型防护档位（normal=不一致拒绝+未知转人工；strict=一律拒绝；off=仅记录）。仅管理员可见可改。
  const GUARD_LABEL: Record<string, string> = { normal: "标准（推荐）", strict: "严格", off: "关闭" }
  const GUARD_DESC: Record<string, string> = {
    normal: "文件名后缀与实际内容不一致 → 拒绝；无法识别内容类型 → 转人工审批",
    strict: "后缀与内容不一致、或无法识别内容类型 → 一律拒绝",
    off: "只记录嗅探结果，不影响规则判定（回退开关）",
  }
  const [guard, setGuard] = useState<string | null>(null)
  useEffect(() => {
    if (role !== "管理员") return
    void (async () => {
      try { const r = await fetch("/api/admin/config", { cache: "no-store" }); const d = await r.json() as { ldap?: { contentTypeGuard?: string } | null }; if (r.ok) setGuard(d.ldap?.contentTypeGuard || "normal") } catch { /* 配置读取失败时隐藏该区块 */ }
    })()
  }, [role])
  async function saveGuard(value: string) {
    try {
      const response = await fetch("/api/admin/config", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ contentTypeGuard: value }) })
      const data = await response.json() as ApiError & { contentTypeGuard?: string }
      if (!response.ok) throw new Error(data.error || "保存失败")
      setGuard(data.contentTypeGuard || value); setNotice(`内容类型防护档位已切换为「${GUARD_LABEL[value] || value}」，变更已写入审计台账`)
    } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "保存失败") }
  }
  const emptyDraft = { name: "", extensions: "", minSizeBytes: "", maxSizeBytes: "", action: "转人工审批", scope: "全员", approverEmails: "", priority: String(items.length + 1) }
  const [draft, setDraft] = useState(emptyDraft)
  function openCreate() { if (role !== "管理员") { setError("仅管理员可维护审批规则"); return } setEditing(null); setDraft(emptyDraft); setOpen(true) }
  function openEdit(item: RuleItem) { if (role !== "管理员") { setError("仅管理员可维护审批规则"); return } setEditing(item); setDraft({ name: item.name, extensions: (item.extensions || []).join(", "), minSizeBytes: item.minSizeBytes ? String(item.minSizeBytes / 1024 / 1024) : "", maxSizeBytes: item.maxSizeBytes ? String(item.maxSizeBytes / 1024 / 1024) : "", action: item.action, scope: item.scope === "全员" ? "全员" : "部门匹配", approverEmails: (item.approverEmails || []).join(", "), priority: String(item.priority ?? items.indexOf(item) + 1) }); setOpen(true) }
  async function save() { if (!draft.name.trim()) return; const payload: Record<string, unknown> = { name: draft.name.trim(), extensions: draft.extensions.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean), minSizeBytes: draft.minSizeBytes ? Math.round(Number(draft.minSizeBytes) * 1024 * 1024) : undefined, maxSizeBytes: draft.maxSizeBytes ? Math.round(Number(draft.maxSizeBytes) * 1024 * 1024) : undefined, action: draft.action, scope: draft.scope === "全员" ? "ALL" : "DEPARTMENT", approverEmails: draft.approverEmails.split(",").map((s) => s.trim()).filter(Boolean), priority: Number(draft.priority) || 99 }; try { const response = await fetch(editing ? `/api/rules/${editing.id}` : "/api/rules", { method: editing ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as ApiError & { id?: string }; if (!response.ok) throw new Error(data.error || "保存规则失败"); await refresh(); setOpen(false); setNotice(`${editing ? `${editing.id} 已更新` : `${data.id} 已创建`}，变更已写入审计台账`) } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "保存规则失败") } }
  async function remove(item: RuleItem) { if (role !== "管理员") { setError("仅管理员可维护审批规则"); return } if (!window.confirm(`确认删除规则 ${item.id}（${item.name}）？该操作会写入审计台账，且不可恢复。`)) return; try { const response = await fetch(`/api/rules/${item.id}`, { method: "DELETE" }); const data = await response.json() as ApiError; if (!response.ok) throw new Error(data.error || "删除规则失败"); await refresh(); setNotice(`${item.id} 已删除并写入审计台账`) } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "删除规则失败") } }
  function toggle(id: string) { const item = items.find((candidate) => candidate.id === id); if (item) void onToggleRequest(id, !item.enabled) }
  async function onToggleRequest(id: string, enabled: boolean) { try { const response = await fetch(`/api/rules/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled }) }); const data = await response.json() as ApiError; if (!response.ok) throw new Error(data.error || "规则更新失败"); await refresh(); setNotice(`${id} 状态已更新并写入审计台账`) } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "规则更新失败") } }
  return <div className="space-y-7"><SectionTitle eyebrow="规则引擎" title="审批规则" description="规则按优先级从上到下匹配，命中即停止；未命中任何规则时始终转人工审批。规则可指派指定审批人。" actions={<Button onClick={openCreate}><Plus />新建规则</Button>} /><div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><b>安全兜底已开启：</b>未命中规则的文件不会自动放行，将进入人工审批。自动通过规则将直接触发外传。</div>
  {guard && <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">内容类型防护</h2><p className="mt-1 text-xs text-slate-500">上传时嗅探文件首 512 字节的「魔数」签名，与文件名后缀比对，防止把 <code>合同.pdf</code> 改名成 <code>合同.bin</code> 绕过审批。嗅探结果一律落库并写入审计。</p><div className="mt-4 flex flex-wrap items-center gap-3"><Select value={guard} onValueChange={(value) => role === "管理员" ? void saveGuard(value) : setError("仅管理员可调整防护档位")}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent>{["normal","strict","off"].map((value) => <SelectItem key={value} value={value}>{GUARD_LABEL[value]}</SelectItem>)}</SelectContent></Select><span className="text-sm text-slate-600">{GUARD_DESC[guard]}</span></div></div>}<div className="space-y-3">{items.map((item,index)=><div key={item.id} className={`grid gap-4 rounded-2xl border bg-white p-5 lg:grid-cols-[48px_1fr_140px_110px_110px_auto] lg:items-center ${item.enabled?"border-slate-200":"opacity-60"}`}><div className="grid size-10 place-items-center rounded-xl bg-slate-100 font-semibold">{item.priority ?? index+1}</div><div><div className="flex items-center gap-2"><h2 className="font-semibold">{item.name}</h2><span className="text-xs text-slate-400">{item.id}</span></div><p className="mt-2 text-sm text-slate-600">{item.condition}</p></div><Badge variant="outline" className={ruleActionStyle[item.action] || statusStyle["PENDING_APPROVAL"]}>{item.action}</Badge><span className="text-sm text-slate-500">{item.scope}</span><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={()=>toggle(item.id)}>{item.enabled?"已启用":"已停用"}</Button><Button variant="ghost" size="sm" onClick={()=>openEdit(item)}><Pencil className="size-4" /></Button><Button variant="ghost" size="sm" className="text-rose-600 hover:text-rose-700" onClick={()=>void remove(item)}><Trash2 className="size-4" /></Button></div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">兜底规则</h2><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="text-sm font-medium">未命中任何规则</p><p className="mt-1 text-xs text-slate-500">固定动作，不允许关闭</p></div><Badge className="bg-amber-100 text-amber-800">转人工审批</Badge></div></div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? `编辑规则 ${editing.id}` : "新建审批规则"}</DialogTitle><DialogDescription>规则按优先级匹配：先比较扩展名与大小范围，再按部门范围过滤，命中即停止。</DialogDescription></DialogHeader><div className="space-y-3"><Input placeholder="规则名称" value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})} /><Input placeholder="扩展名，逗号分隔（留空表示任意）" value={draft.extensions} onChange={(e)=>setDraft({...draft,extensions:e.target.value})} /><div className="grid grid-cols-2 gap-3"><Input type="number" min="0" placeholder="最小大小（MB，留空=不限）" value={draft.minSizeBytes} onChange={(e)=>setDraft({...draft,minSizeBytes:e.target.value})} /><Input type="number" min="0" placeholder="最大大小（MB，留空=不限）" value={draft.maxSizeBytes} onChange={(e)=>setDraft({...draft,maxSizeBytes:e.target.value})} /></div><p className="text-xs leading-5 text-slate-500">大小区间含义：<b>最小 = 下限</b>（文件需 ≥ 该值），<b>最大 = 上限</b>（文件需 ≤ 该值）。两个都留空表示不限大小；动作选「自动通过」且区间留空时，该后缀文件命中即自动通过并立即外传。</p><div className="grid grid-cols-2 gap-3"><Select value={draft.action} onValueChange={(action)=>setDraft({...draft,action})}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["转人工审批","自动通过","拒绝"].map((a)=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select><Select value={draft.scope} onValueChange={(scope)=>setDraft({...draft,scope})}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="全员">全员</SelectItem><SelectItem value="部门匹配">部门匹配</SelectItem></SelectContent></Select></div><Input placeholder="指定审批人邮箱，逗号分隔（留空表示按角色轮询）" value={draft.approverEmails} onChange={(e)=>setDraft({...draft,approverEmails:e.target.value})} /><Input type="number" min="1" placeholder="优先级（数字越小越先匹配）" value={draft.priority} onChange={(e)=>setDraft({...draft,priority:e.target.value})} /></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button disabled={!draft.name.trim()} onClick={()=>void save()}>{editing ? "保存修改" : "创建规则"}</Button></DialogFooter></DialogContent></Dialog></div>
}
